Semi Transparent shader implementation
Project-10/OpenRT pull request #13
Opened 2020-09-09 08:57 UTC by ezanageressu

2020-09-11 12:52 UTC, ereator requested changes
Just a small modification is needed, otherwise is good!

2020-09-11 12:52 UTC, ereator commented on modules/core/ShaderSSLT.h
> +
I think it makes sense to add one more member-variable `m_opacity` here and initialize in the constructor as an argument

2020-09-11 12:52 UTC, ereator commented on modules/core/ShaderSSLT.cpp
> +		res = color + reTrace(I);
This one makes the object to glow: you add light here. The better choice would be to mix the color of the object and the color of the re-traced ray via a linear combination alpha * color + beta * reTrace(I), where alpha + beta = 
For the coefficients we can use the `m_opacity` variable , e.g. as follows:
`res = m_opacity * color + (1.0f - m_opacity) * reTrace(I);`

2020-09-11 12:52 UTC, ereator commented on modules/core/ShaderSSLT.h
> +		const Vec3f exitColor = RGB(0.4f, 0.4f, 0.4f);
I would add prefix `m_` here as this is a member-variable

2020-09-15 03:44 UTC, ezanageressu commented
I have applied the changes!

2020-09-17 16:05 UTC, merged